4l3x-suvnet/todo_calendar

index.html
Added header block to index.html
=> Header added

index.html
Sidebar template added to index.html
=> Sidebar added

index.html
=> Added placeholders for calendar grid.

css/desktop.css, index.html
=> 24 display aside and main besides each other and give it styling

css/desktop.css
=> Gave the grid dates a box

css/desktop.css
=> Current date is now highlighted

css/desktop.css, index.html, js/weather.js
=> Today's forecast added

index.html
=> 26 load icons for arrow place holders

index.html
=> index.html fixed

css/global.css, index.html
=> Add a new font family quicksand put in html global

index.html, js/todos.js
=> todos can now be added

css/desktop.css, js/todos.js
=> Todos can now be removed

index.html, js/calendar.js
close #12  Co-authored-by: 4l3x-suvnet <4l3x-suvnet@users.noreply.github.com>
=> user can navigate month using arrows

css/desktop.css, js/calendar.js
=> 18 grid filling days next month

index.html
close #13 Added a title for the calendar and put that name in the header as well.
=> Added title for calendar

index.html, js/todos.js
close #55 Added Id, description, date and local time to the todo object.
=> 55 expand the todo object

css/desktop.css, index.html, js/weather.js
=> Weather now loads based on geolocation

css/desktop.css, js/calendar.js
=> Highlight selected day in grid

css/desktop.css
quick, can change colors etc later
=> Added header styling

index.html, js/aside.js, js/calendar.js
Please look at the refactor, u might disslike it?
=> Refactored calendar a bit, and added aside func

js/weather.js
=> Weather now loads even if user blocks the prompt

css/desktop.css, index.html, js/calendar.js, js/holidays.js
=> Holidays added (6th June manually added)

js/calendar.js
=> Clicking another day in the grid now de-selects previously clicked day

js/calendar.js, js/todos.js
close #11 Todos are now connected to the calendar
=> Todo is now on the right date

js/todos.js
=> saved todos now also renders

css/desktop.css, css/global.css, index.html, js/aside.js
close #89 
With the CSS overhaul, the new Add todo popup loads behind main for some reason.
=> Page overhauled but appears to be somewhat broken?

css/desktop.css
=> Todo date cards are now split

css/desktop.css, js/todos.js
=> Add-todo-popup stylized, modal-fade added

css/desktop.css, index.html, js/calendar.js, js/todos.js
=> Populate and remove todos based on selected date

js/calendar.js
=> Fixed bugg, added comments

css/colormode.css, css/desktop.css, css/global.css, index.html, js/calendar.js, js/colormode.js
First step to a dark/light- mode. Just added some random colors for light mode for now.
=> 20 feature darklight mode

js/calendar.js, js/todos.js
=> added sort, and removed some console.log

css/colormode.css, css/desktop.css, css/global.css, index.html, js/calendar.js, js/colormode.js
close #123 
Toggle added for light/dark- mode. Dark mode is set as default. We might want to look into saving theme to LocalStorage.
=> Theme toggle added

css/colormode.css, css/desktop.css, css/mobile.css, css/tablet.css, index.html, js/todos.js
close #116 
Mobile: Calendar hidden completely, min-height set to 95vh > the page becomes scrollable after that
Tablet: Calendar is shown beneath todos and the calendar grid becomes a bit smaller
Todo form popup should work properly on different screens, too.
=> 116 responsiveness

css/colormode.css, css/desktop.css, js/calendar.js
=> Nr of todos is now displayed in grid

js/aside.js, js/calendar.js, js/todos.js
=>  Todocounter updates on edits etc + minor buggs

css/desktop.css, js/calendar.js
close #135
Result:
Need to fix the styling a bit more, but it's a good start
=> Hover effect on class todo-counter in place

css/desktop.css
close #139  Long titles without whitespace now shows the whole text.
=> Long titles with no space shows whole text now

css/colormode.css
=> Colors now overlap correctly

js/calendar.js, js/colormode.js
=> Theme now saves to and loads from local storage

css/colormode.css, css/desktop.css, index.html
=> Todo description now has a textarea with a 150 character limit

js/todos.js
=> Should be working :)?

css/colormode.css, css/desktop.css, css/global.css, index.html
=> hightlight prev, next, add-todo button when mouse hover

js/todos.js
=> isDone should work as intended

css/colormode.css, css/desktop.css, js/weather.js
=> Hovering over weather divs now shows additional weather information

index.html, js/calendar.js, js/colormode.js, js/globalvariables.js, js/holidays.js, js/todos.js, js/weather.js
close #156  Moved global variables. Though some global variables like 
let idCounter = todoItems.length == 0 ? 0 : todoItems[todoItems.length - 1].id + 1;
I was unable to move without getting error messages in the website console.
!!!DO NOT MERGE YET!!!
=> Moved global variables to global file

css/colormode.css
=> color fixes

css/desktop.css
=> mask now has a gradient at the top and bottom

css/desktop.css
=> Some clean up and fixes

css/desktop.css
=> grid now has a thin border
